package com.taskOrchestrator.app.auth.application;

import com.taskOrchestrator.app.auth.application.RefreshTokenService;
import com.taskOrchestrator.app.auth.domain.RefreshToken;
import com.taskOrchestrator.app.auth.domain.User;
import com.taskOrchestrator.app.auth.domain.UserRepository;
import com.taskOrchestrator.app.auth.infrastructure.jwt.JwtUtil;
import com.taskOrchestrator.app.auth.web.AuthAccessResponse;
import com.taskOrchestrator.app.auth.web.RegisterRequest;
import com.taskOrchestrator.app.common.exception.DuplicateEmailException;
import com.taskOrchestrator.app.common.exception.DuplicateUsernameException;
import org.springframework.http.HttpStatus;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.server.ResponseStatusException;

@Service
public class AuthService {
    private final JwtUtil jwtUtil;
    private final UserRepository userRepository;
    private final PasswordEncoder passwordEncoder;
    private final RefreshTokenService refreshTokenService;

    public AuthService(
            JwtUtil jwtUtil,
            UserRepository userRepository,
            PasswordEncoder passwordEncoder,
            RefreshTokenService refreshTokenService
    ) {

        this.jwtUtil = jwtUtil;
        this.userRepository = userRepository;
        this.passwordEncoder = passwordEncoder;
        this.refreshTokenService = refreshTokenService;
    }

    //Authenticate user. Access token: generated by JwtUtil
    //Refresh token: generated and persisted by RefreshTokenService
    @Transactional
    public AuthAccessResponse login(String username, String password) {
        User user = userRepository
                .findByUsername(username)
                .orElseThrow(() ->
                                new ResponseStatusException(
                                        HttpStatus.UNAUTHORIZED,
                                        "Invalid username or password"));

        //BCrypt password verification.
        if (!passwordEncoder.matches(password, user.getPassword())) {
            throw new ResponseStatusException(
                    HttpStatus.UNAUTHORIZED,
                    "Invalid username or password");
        }

        return createAuthResponse(user);
    }

    //Refreshes authentication using refresh-token rotation.
    @Transactional(noRollbackFor = ResponseStatusException.class)
    public AuthAccessResponse refresh(String rawRefreshToken) {
        //Check for reuse BEFORE calling validate().
        //A revoked refresh token being presented again is a potential
        //token-theft/reuse event. All active sessions for that user must be revoked.
        if (refreshTokenService.detectReuse(rawRefreshToken)) {
            RefreshToken reusedToken = refreshTokenService.findByRawTokenForReuse(rawRefreshToken);
            if (reusedToken != null && reusedToken.getUser() != null) {
                refreshTokenService.revokeAllForUser(reusedToken.getUser());}
            throw new ResponseStatusException(
                    HttpStatus.UNAUTHORIZED,
                    "Refresh token reuse detected"
            );
        }

        //Token has not previously been revoked. validate() verifies:JWT signature,
        //JWT expiration, refresh token type, token exists in DB, token is not revoked, database expiration
        RefreshToken storedToken = refreshTokenService.validate(rawRefreshToken);
        User user = storedToken.getUser();
        if (user == null) {
            throw new ResponseStatusException(
                    HttpStatus.UNAUTHORIZED,
                    "Invalid refresh token"
            );
        }

        //Consume/revoke the current refresh token.
        refreshTokenService.revoke(storedToken);

        //Generate: Access Token B, Refresh Token B and persist Refresh Token B.
        return createAuthResponse(user);
    }

    //Registers a new user
    @Transactional
    public AuthAccessResponse register(RegisterRequest request) {
        if (userRepository.existsByUsername(request.username())) {
            throw new DuplicateUsernameException(
                    "Username already exists"
            );
        }

        if (userRepository.existsByEmail(request.email())) {
            throw new DuplicateEmailException(
                    "Email already exists"
            );
        }

        //Password is hashed before being stored.
        User user = User.builder()
                .username(request.username())
                .fullName(request.fullName())
                .email(request.email())
                .password(passwordEncoder.encode(request.password()))
                .role(User.Role.USER)
                .build();

        userRepository.save(user);
        return createAuthResponse(user);
    }

    public void logout(String username, String rawRefreshToken) {
        RefreshToken refreshToken = refreshTokenService.validate(rawRefreshToken);
        User user = refreshToken.getUser();

       //Ensure the refresh token belongs to the authenticated user.
        if (!user.getUsername().equals(username)) {
            throw new ResponseStatusException(
                    HttpStatus.UNAUTHORIZED,
                    "Invalid refresh token"
            );
        }
        refreshTokenService.revoke(refreshToken);
    }

    public void logoutAll(String username) {
        User user = userRepository.findByUsername(username)
                .orElseThrow(() -> new ResponseStatusException
                        (HttpStatus.UNAUTHORIZED, "User not found"));

        refreshTokenService.revokeAllForUser(user);
    }

    //Creates an access token and a database-backed refresh token.
    private AuthAccessResponse createAuthResponse(User user) {
        String accessToken = jwtUtil.generateAccessToken(
                        user.getUsername(),
                        user.getRole()
        );

        String refreshToken = jwtUtil.generateRefreshToken(
                        user.getUsername(),
                        user.getRole()
        );

        refreshTokenService.create(
                user,
                refreshToken
        );

        return new AuthAccessResponse(
                accessToken,
                refreshToken
        );
    }
}