package com.taskOrchestrator.app.auth.application;

import com.taskOrchestrator.app.auth.application.RefreshTokenService;
import com.taskOrchestrator.app.auth.domain.RefreshToken;
import com.taskOrchestrator.app.auth.domain.User;
import com.taskOrchestrator.app.auth.domain.UserRepository;
import com.taskOrchestrator.app.auth.infrastructure.jwt.JwtUtil;
import com.taskOrchestrator.app.auth.web.AuthAccessResponse;
import com.taskOrchestrator.app.auth.web.RegisterRequest;
import com.taskOrchestrator.app.common.exception.DuplicateEmailException;
import com.taskOrchestrator.app.common.exception.DuplicateUsernameException;
import org.springframework.http.HttpStatus;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.server.ResponseStatusException;

@Service
public class AuthService {

    private final JwtUtil jwtUtil;
    private final UserRepository userRepository;
    private final PasswordEncoder passwordEncoder;
    private final RefreshTokenService refreshTokenService;

    public AuthService(
            JwtUtil jwtUtil,
            UserRepository userRepository,
            PasswordEncoder passwordEncoder,
            RefreshTokenService refreshTokenService
    ) {

        this.jwtUtil = jwtUtil;
        this.userRepository = userRepository;
        this.passwordEncoder = passwordEncoder;
        this.refreshTokenService = refreshTokenService;
    }

    /**
     * Authenticates a user.
     * Access token: generated by JwtUtil
     * Refresh token: generated and persisted by RefreshTokenService
     */
    @Transactional
    public AuthAccessResponse login(String username, String password) {
        User user = userRepository
                .findByUsername(username)
                .orElseThrow(() ->
                                new ResponseStatusException(
                                        HttpStatus.UNAUTHORIZED,
                                        "Invalid username or password"));

        //BCrypt password verification.
        if (!passwordEncoder.matches(password, user.getPassword())) {
            throw new ResponseStatusException(
                    HttpStatus.UNAUTHORIZED,
                    "Invalid username or password");
        }

        return createAuthResponse(user);
    }

    /**
     * Refreshes authentication using refresh-token rotation.
     * Flow:
     * Existing refresh token
     *          ↓
     * RefreshTokenService.rotate()
     *          ↓
     * Existing token revoked
     *          ↓
     * New refresh token created
     *          ↓
     * New access token created
     *
     * noRollbackFor: on reuse detection, RefreshTokenService revokes every
     * session and throws — those revocations must commit even though we
     * exit via an exception.
     */
    @Transactional(noRollbackFor = ResponseStatusException.class)
    public AuthAccessResponse refresh(String refreshToken) {
        RefreshTokenService.RefreshTokenRotation rotation =
                refreshTokenService.rotate(refreshToken);

        User user = rotation.user();
        String newRefreshToken = rotation.refreshToken();

        //Access tokens are intentionally short-lived
        // Every successful refresh creates a new access token.
        String newAccessToken =
                jwtUtil.generateAccessToken(
                        user.getUsername(),
                        user.getRole()
                );

        return new AuthAccessResponse(
                newAccessToken,
                newRefreshToken
        );
    }

    //Registers a new user
    @Transactional
    public AuthAccessResponse register(RegisterRequest request) {
        if (userRepository.existsByUsername(request.username())) {
            throw new DuplicateUsernameException(
                    "Username already exists"
            );
        }

        if (userRepository.existsByEmail(request.email())) {
            throw new DuplicateEmailException(
                    "Email already exists"
            );
        }


        //Password is hashed before being stored.
        User user = User.builder()
                .username(request.username())
                .fullName(request.fullName())
                .email(request.email())
                .password(passwordEncoder.encode(request.password()))
                .role(User.Role.USER)
                .build();

        userRepository.save(user);
        return createAuthResponse(user);
    }

    //Creates an access token and a database-backed refresh token.
    private AuthAccessResponse createAuthResponse(User user) {
        String accessToken = jwtUtil.generateAccessToken(
                        user.getUsername(),
                        user.getRole());

        String refreshToken = refreshTokenService.create(user);
        return new AuthAccessResponse(
                accessToken,
                refreshToken
        );
    }
}