spring.application.name=task-orchestrator
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
server.port=8080
jwt.secret=${JWT_SECRET}
jwt.expiration=3600000
#For--Prod
#jwt.access-expiration=900000
#jwt.refresh-expiration=604800000
#For--Testing
jwt.access-expiration=30000
jwt.refresh-expiration=600000

